const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = [
    './routes/authRoutes',
    './routes/evaluationRoutes',
    './routes/heartbeatRoutes',
    './routes/jobRoutes',
    './routes/packRoutes',
    './routes/processRoutes',
    './routes/questionRoutes',
    './routes/settingsRoutes',
    './routes/testRoutes',
];
const doc = {
    info: {
        version: '1.0.0',
        title: 'ATS Documentation',
        description:
            'Documentation automatically generated by the <b>swagger-autogen</b> module.',
    },
    basePath: '/',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],

    definitions: {
        User: {
            email: { type: 'String', required: true, unique: true },
            password: { type: 'String' },
            phone: { type: 'String', unique: true },
            job: { type: 'String' },
            attempts: { type: 'Number', required: true, default: 0 },
            role: { type: 'ObjectId', ref: 'role', required: true },
            firstName: { type: 'String', required: true },
            lastName: { type: 'String', required: true },
            avatar: { type: 'String', required: true },
            active: { type: 'Boolean', required: true, default: true },
            createdAt: { type: 'Date', default: 'Date.now' },
            lastConnection: { type: 'Date' },
            Login: {
                $email: 'khaled@gmail.com',
                $password: 'strongpassword',
            },
        },
        Login: {
            $email: 'khaled@gmail.com',
            $password: 'strongpassword',
        },
    },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js');
});
